Add assertions
AY2425S1-CS2103T-F11-1/tp pull request #113
Opened 2024-10-22 09:01 UTC by bbbbcccd

Fixes #98

2024-10-22 12:55 UTC, karthickkc approved these changes
Lgtm!!

2024-10-22 12:55 UTC, karthickkc commented on src/main/java/seedu/address/logic/commands/DeleteConcertCommand.java
> + * Deletes a concert identified using it's displayed index from the address book.
actually this should be its ah but wtv

2024-10-22 14:10 UTC, wes-w-z-h requested changes
lgtm with minor changes!

2024-10-22 14:10 UTC, wes-w-z-h commented on src/main/java/seedu/address/logic/commands/DeleteConcertContactCommand.java
> +        requireNonNull(concertIndex);
for this can use requireAllNonNull instead of multiple requireNonNulls

2024-10-22 14:10 UTC, wes-w-z-h commented on src/main/java/seedu/address/logic/parser/AddConcertCommandParser.java
> +        assert argMultimap.getValue(PREFIX_DATE).isPresent() : "Prefix for date should be present";
should add this chunk below the verifyNoDuplicatePrefixes

2024-10-22 14:10 UTC, wes-w-z-h commented on src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
> +        assert argMultimap.getValue(PREFIX_ROLE).isPresent() : "Prefix for role should be present";
same here should move it down

2024-10-22 14:10 UTC, wes-w-z-h commented on src/main/java/seedu/address/logic/parser/AddConcertCommandParser.java
>      }
Can consider adding assertions for isValid for the fields passed to the constructor of Concert similar to `AddPersonCommandParser`

2024-10-22 14:10 UTC, wes-w-z-h commented on src/main/java/seedu/address/logic/parser/FindConcertCommandParser.java
> +        assert argMultimap.getValue(PREFIX_NAME).isPresent() : "Prefix for name must be present";
should move it below verifyDuplicatePrefixes

2024-10-22 14:10 UTC, wes-w-z-h commented on src/main/java/seedu/address/logic/parser/FindPersonCommandParser.java
> +        assert argMultimap.getValue(PREFIX_NAME).isPresent() || argMultimap.getValue(PREFIX_ROLE).isPresent()
should be below verifyDuplicatePrefixes

2024-10-23 13:29 UTC, bbbbcccd commented on src/main/java/seedu/address/logic/commands/DeleteConcertCommand.java
> + * Deletes a concert identified using it's displayed index from the address book.
genius 💯

2024-10-23 13:58 UTC, bbbbcccd commented
Made changes as requested and fixed some minor issues (typos etc.)

2024-10-23 15:57 UTC, wes-w-z-h approved these changes

2024-10-23 15:59 UTC, merged