Add edit concert command
AY2425S1-CS2103T-F11-1/tp pull request #114
Opened 2024-10-22 12:44 UTC by wes-w-z-h

Fixes #101

2024-10-22 13:03 UTC, karthickkc requested changes

2024-10-22 13:03 UTC, karthickkc commented on src/main/java/seedu/address/logic/commands/EditConcertCommand.java
> +     * Creates and returns a {@code Cocnert} with the details of {@code concertToEdit}
same here

2024-10-22 13:03 UTC, karthickkc commented on src/main/java/seedu/address/logic/commands/EditConcertCommand.java
> +     * @param index of the conert to edit.
minor typo should be concert

2024-10-22 13:03 UTC, karthickkc commented on src/main/java/seedu/address/logic/commands/EditConcertCommand.java
> +     * Stores the details to edit the concert with. Each non-empty field value will repalce the
typo should be replace

2024-10-22 13:13 UTC, karthickkc commented on src/main/java/seedu/address/logic/commands/EditConcertCommand.java
> +
also for this one there should be space before the prefix_address and prefix_date

2024-10-22 14:06 UTC, karthickkc approved these changes

2024-10-23 14:17 UTC, bbbbcccd submitted a review, later dismissed
lgtm with 1 typo

2024-10-23 14:17 UTC, bbbbcccd commented on src/main/java/seedu/address/logic/parser/EditConcertCommandParser.java
> + * Parses input arguments adn creates a new EditConcertCommand object.
Typo adn -> and

2024-10-24 01:59 UTC, merged