Assign roles
AY2425S1-CS2103T-F11-1/tp pull request #53
Opened 2024-10-10 15:59 UTC by karthickkc

Added functionality to assign roles for each contact

2024-10-10 16:02 UTC, bbbbcccd reviewed
Fix check style and javadocs

2024-10-10 17:34 UTC, karthickkc commented
fixes #43

2024-10-11 02:15 UTC, wes-w-z-h requested changes
lgtm minor changes

2024-10-11 02:15 UTC, wes-w-z-h commented on src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
> +//import seedu.address.model.person.Role;
dead code should be removed

2024-10-11 03:51 UTC, wes-w-z-h approved these changes
lgtm!! 👍👍👍

2024-10-11 03:52 UTC, merged