Add link command
AY2425S1-CS2103T-F11-1/tp pull request #71
Opened 2024-10-16 14:36 UTC by karthickkc

Links a Person to a Concert

2024-10-16 14:51 UTC, wes-w-z-h requested changes
Insufficient tests, need a new issue for storage of concert contacts

2024-10-16 15:14 UTC, wes-w-z-h requested changes

2024-10-16 15:14 UTC, wes-w-z-h commented on src/test/java/seedu/address/logic/commands/LinkCommandTest.java
why is it all commented out?

2024-10-16 15:14 UTC, wes-w-z-h commented on src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
list command parser or link command parser

2024-10-16 15:14 UTC, wes-w-z-h commented on src/test/java/seedu/address/testutil/TypicalIndexes.java
> +
dont need a new line here

2024-10-16 16:00 UTC, wes-w-z-h commented
![image](https://github.com/user-attachments/assets/83f116f9-fe12-4d93-bb2d-49472c816390)
Uncaught exception for invalid index

2024-10-17 01:28 UTC, wes-w-z-h requested changes
<img width="1372" alt="image" src="https://github.com/user-attachments/assets/a0d499c5-034e-4090-9362-559975843c47">
Doesn't do massOps so this command should throw an error, can consider adding more test cases to catch this sort of inputs including invalid c/INDEX

2024-10-17 01:49 UTC, hj235 commented on src/main/java/seedu/address/logic/commands/LinkCommand.java
> +             + PREFIX_CONCERT + "INDEX (must be a positive integer)\n"
Can u change the text to PERSONINDEX and CONCERTINDEX

2024-10-17 02:12 UTC, wes-w-z-h approved these changes
lgtm 🥳🤩

2024-10-17 02:13 UTC, merged